config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :notes, only: [:index, :new, :create, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  
  belongs_to :user
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :image, presence: true
  validates :body, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :notes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    notes_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    note = Note.find(params[:note_id])
    comment = current_user.comments.new(comment_params)
    comment.note_id = note.id
    comment.save
    redirect_to note_path(note)
  end
  
  def destroy
    Comment.find_by(id: params[:id], note_id: params[:note_id]).destroy
    redirect_to note_path(params[:note_id])
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:comment)  
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    note = Note.find(params[:note_id])
    favorite = current_user.favorites.new(note_id: note.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    note = Note.find(params[:note_id])
    favorite = current_user.favorites.find_by(note_id: note.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  
  def index
    @notes = Note.page(params[:page]).reverse_order
  end
  
  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def show
    @note = Note.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_path
  end
  
  private
  
  def note_params
    params.require(:note).permit(:title, :image, :body)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @notes = @user.notes.page(params[:page]).reverse_order
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/top.html.erb
<div class="col-md-6 mx-auto mt-5">
  <h1>welcome to <strong>Outputter</strong>  !!</span></h1>
  <p>In  <span class="glyphicon glyphicon-book"></span><strong>Outputter</strong>, </p>
  <p>SNS community that indiscriminately stimulates the appetite of sensible citizens.</p>
  <div class="row">
   <p class="ml-3"><a class="btn btn-info" href="/users/sign_in">Log in</a></p>
   <p class="ml-3"><a class="btn btn-success" href="/users/sign_up">Sign Up</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Outputter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-1" href="/"><%= image_tag 'logo.png' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to '投稿一覧', notes_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_note_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_list.html.erb
<div class="containar p-5">
  <div class="card-deck row-eq-height ">
    <% notes.each do |note| %>
      <div class="col-md-3">
        <div class="card ">
          <%= link_to note_path(note.id) do %>
            <%= attachment_image_tag note, :image, :fill, 1000, 500, class:"card-img-top img-responsive" %>
          <% end %>
          <div class="card-body">
            <div class-"row">
              <div class="col-10">
                <p class="card-title">
                  <%= link_to(note_path(note.id), class:"text-dark") do %>
                    <strong><h3><%= note.title %></h3></strong>
                  <% end %>
                </p>
                <%= attachment_image_tag note.user, :profile_image, fallback: "no_image.jpg", style: "height: 30px; width:30px;", class:"rounded-circle"; %>
                <span><strong><%=link_to note.user.name, user_path(note.user) %></strong></span>
                <time><%= note.updated_at.strftime("%Y-%m-%d %H:%M") %></time>
                <div>
                  <%= link_to "#{note.comments.count} コメント | ", note_path(note.id), class:"text-dark" %>
                  <% if note.favorited_by?(current_user) %>
                    <span>
                      <%= link_to note_favorites_path(note), method: :delete do %>
                        <i class="fas fa-heart"></i><%= note.favorites.count %> いいね
                      <% end %>
                    </span>
                    <% else %>
                    <span>
                      <%= link_to note_favorites_path(note), method: :post do %>
                        <i class="far fa-heart"></i><%= note.favorites.count %> いいね
                      <% end %>
                    </span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        </br>
      </div>
    <% end %>
    <div class="mx-auto">
      <%= paginate notes %>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<%= render 'notes/list', notes: @notes %>

app/views/notes/new.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0"記事投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @note.errors.any? %>
          <%= @note.errors.count %>件のエラーが発生しました
          <% @note.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @note, local:true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
          </div>
          <%= f.text_area :body, class:"form-control", rows:"3", placeholder:"本文" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="post-detail py-5 bg-light">
  <div class="card w-75 mx-auto mt-4 shadow-lg">
    <%= attachment_image_tag @note, :image, :fill, 1000, 500, style: "height: 300px; width:100%;", class:"card-img-top img-responsive"; %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag @note.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(note_path(@note.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= @note.title %></span></strong>
            <% end %>
          </p>
          <p class="card-title">本文：<%= @note.body %></p>
          <span><i class="fas fa-user"></i> By <%= @note.user.name %> ｜ </span>
          <span><i class="fa fa-calendar"></i> <%= @note.created_at.strftime('%Y/%m/%d') %> ｜ </span>
          <span><i class="fa fa-comment"></i> <%= link_to "#{@note.comments.count}", note_path(@note.id), class:"text-dark" %> ｜ </span>
          <% if @note.favorited_by?(current_user) %>
            <span>
              <%= link_to(note_favorites_path(@note), class:"text-dark", method: :delete) do %>
                <i class="fa fa-heart" aria-hidden="true"></i> <%= @note.favorites.count %>
              <% end %>
            </span>
            <% else %>
            <span>
              <%= link_to(note_favorites_path(@note), class:"text-dark", method: :post) do %>
                <i class="fa fa-heart" aria-hidden="true"></i> <%= @note.favorites.count %>
              <% end %>
            </span>
          <% end %>
          <% if @note.user == current_user %>
            <span> ｜ </span><%= link_to "削除", note_path(@note), class:"text-dark", method: :delete %>
          <% end %>
        </div>
      </div>
      <hr>
      <div class="comments card-text">
        <h4 class="mt-3"><%= @note.comments.count %>件コメント</h4>
        <% @note.comments.each do |comment| %>
          <div class="media border mb-3">
            <%= attachment_image_tag comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"bd-placeholder-img align-self-center mx-3" %>
            <div class="media-body ml-4 p-3">
              <p><%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %></p>
              <p><%= comment.comment %></p>
              <% if comment.user == current_user %>
                <%= link_to "削除", note_comment_path(comment.note, comment), method: :delete, class: "btn btn-danger pull-right" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <hr>
      <div class="new-comment card-text">
        <%= form_with(model:[@note, @comment]) do |f| %>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">コメントする</label>
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
          </div>
          <%= f.submit "送信する", class:"btn btn-lg btn-info mt-2 float-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light py-4 mb-0">プロフィール編集</h5>
      <div class="form-body p-4">
        <%= form_with model: @user, local: true do |f| %>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName", placeholder:"名前"%>
          </div>
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mb-3" %>
          <div class="input-group my-3">
            <label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "w-100" %>
            </label>
          </div>
          <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-info mt-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-container w-75 d-flex mx-auto justify-content-around align-items-center border-bottom py-5">
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class:"rounded-circle"; %>
  <h5 class="profile-name display-4"><%= @user.name %></h5>
  <% if @user.id == current_user.id %>
    <div class="mt-auto">
    <p><%= link_to "プロフィール編集", edit_user_path(@user), class:"text-dark" %></p>
    </div>
  <% end %>
</div>
<%= render 'notes/list', notes: @notes %>